"""Engineering materials: each one's grade, kind and name.

The journal names materials by their game symbol and never says what grade
they are, and the grade decides how many you can hold: 300 of a grade 1
material, down to 100 of a grade 5. Grades are game facts, checked against
the author's journal (117 materials held, eight of them sitting exactly at
their grade's cap, none ever above it) and cross-referenced with EDCD's
public ID tables (github.com/EDCD/FDevIDs).
"""

CAPS = {1: 300, 2: 250, 3: 200, 4: 150, 5: 100}

# symbol -> (grade, kind, name)
MATERIALS = {
    # Encoded
    'bulkscandata': (1, 'Encoded', 'Anomalous Bulk Scan Data'),
    'disruptedwakeechoes': (1, 'Encoded', 'Atypical Disrupted Wake Echoes'),
    'shieldcyclerecordings': (1, 'Encoded', 'Distorted Shield Cycle Recordings'),
    'scrambledemissiondata': (1, 'Encoded', 'Exceptional Scrambled Emission Data'),
    'legacyfirmware': (1, 'Encoded', 'Specialised Legacy Firmware'),
    'encryptedfiles': (1, 'Encoded', 'Unusual Encrypted Files'),
    'fsdtelemetry': (2, 'Encoded', 'Anomalous FSD Telemetry'),
    'shieldsoakanalysis': (2, 'Encoded', 'Inconsistent Shield Soak Analysis'),
    'archivedemissiondata': (2, 'Encoded', 'Irregular Emission Data'),
    'consumerfirmware': (2, 'Encoded', 'Modified Consumer Firmware'),
    'encryptioncodes': (2, 'Encoded', 'Tagged Encryption Codes'),
    'tg_structuraldata': (2, 'Encoded', 'Thargoid Structural Data'),
    'scanarchives': (2, 'Encoded', 'Unidentified Scan Archives'),
    'scandatabanks': (3, 'Encoded', 'Classified Scan Databanks'),
    'industrialfirmware': (3, 'Encoded', 'Cracked Industrial Firmware'),
    'symmetrickeys': (3, 'Encoded', 'Open Symmetric Keys'),
    'tg_shipflightdata': (3, 'Encoded', 'Ship Flight Data'),
    'wakesolutions': (3, 'Encoded', 'Strange Wake Solutions'),
    'tg_compositiondata': (3, 'Encoded', 'Thargoid Material Composition Data'),
    'unknownshipsignature': (3, 'Encoded', 'Thargoid Ship Signature'),
    'emissiondata': (3, 'Encoded', 'Unexpected Emission Data'),
    'shielddensityreports': (3, 'Encoded', 'Untypical Shield Scans '),
    'shieldpatternanalysis': (4, 'Encoded', 'Aberrant Shield Pattern Analysis'),
    'encryptionarchives': (4, 'Encoded', 'Atypical Encryption Archives'),
    'decodedemissiondata': (4, 'Encoded', 'Decoded Emission Data'),
    'encodedscandata': (4, 'Encoded', 'Divergent Scan Data'),
    'hyperspacetrajectories': (4, 'Encoded', 'Eccentric Hyperspace Trajectories'),
    'guardian_moduleblueprint': (4, 'Encoded', 'Guardian Module Blueprint Segment'),
    'guardian_weaponblueprint': (4, 'Encoded', 'Guardian Weapon Blueprint Segment'),
    'ancientbiologicaldata': (4, 'Encoded', 'Pattern Alpha Obelisk Data'),
    'ancientculturaldata': (4, 'Encoded', 'Pattern Beta Obelisk Data'),
    'ancientlanguagedata': (4, 'Encoded', 'Pattern Delta Obelisk Data'),
    'ancienttechnologicaldata': (4, 'Encoded', 'Pattern Epsilon Obelisk Data'),
    'ancienthistoricaldata': (4, 'Encoded', 'Pattern Gamma Obelisk Data'),
    'securityfirmware': (4, 'Encoded', 'Security Firmware Patch'),
    'tg_shipsystemsdata': (4, 'Encoded', 'Ship Systems Data'),
    'tg_residuedata': (4, 'Encoded', 'Thargoid Residue Data'),
    'unknownwakedata': (4, 'Encoded', 'Thargoid Wake Data'),
    'compactemissionsdata': (5, 'Encoded', 'Abnormal Compact Emissions Data'),
    'adaptiveencryptors': (5, 'Encoded', 'Adaptive Encryptors Capture'),
    'classifiedscandata': (5, 'Encoded', 'Classified Scan Fragment'),
    'dataminedwake': (5, 'Encoded', 'Datamined Wake Exceptions'),
    'guardian_vesselblueprint': (5, 'Encoded', 'Guardian Vessel Blueprint Segment'),
    'embeddedfirmware': (5, 'Encoded', 'Modified Embedded Firmware'),
    'shieldfrequencydata': (5, 'Encoded', 'Peculiar Shield Frequency Data'),
    # Manufactured
    'basicconductors': (1, 'Manufactured', 'Basic Conductors'),
    'chemicalstorageunits': (1, 'Manufactured', 'Chemical Storage Units'),
    'compactcomposites': (1, 'Manufactured', 'Compact Composites'),
    'crystalshards': (1, 'Manufactured', 'Crystal Shards'),
    'gridresistors': (1, 'Manufactured', 'Grid Resistors'),
    'guardian_powercell': (1, 'Manufactured', 'Guardian Power Cell'),
    'guardian_sentinel_wreckagecomponents': (1, 'Manufactured', 'Guardian Sentinel Wreckage Components'),
    'heatconductionwiring': (1, 'Manufactured', 'Heat Conduction Wiring'),
    'mechanicalscrap': (1, 'Manufactured', 'Mechanical Scrap'),
    'salvagedalloys': (1, 'Manufactured', 'Salvaged Alloys'),
    'temperedalloys': (1, 'Manufactured', 'Tempered Alloys'),
    'wornshieldemitters': (1, 'Manufactured', 'Worn Shield Emitters'),
    'chemicalprocessors': (2, 'Manufactured', 'Chemical Processors'),
    'conductivecomponents': (2, 'Manufactured', 'Conductive Components'),
    'filamentcomposites': (2, 'Manufactured', 'Filament Composites'),
    'uncutfocuscrystals': (2, 'Manufactured', 'Flawed Focus Crystals'),
    'galvanisingalloys': (2, 'Manufactured', 'Galvanising Alloys'),
    'guardian_powerconduit': (2, 'Manufactured', 'Guardian Power Conduit'),
    'heatdispersionplate': (2, 'Manufactured', 'Heat Dispersion Plate'),
    'heatresistantceramics': (2, 'Manufactured', 'Heat Resistant Ceramics'),
    'hybridcapacitors': (2, 'Manufactured', 'Hybrid Capacitors'),
    'mechanicalequipment': (2, 'Manufactured', 'Mechanical Equipment'),
    'shieldemitters': (2, 'Manufactured', 'Shield Emitters'),
    'unknowncarapace': (2, 'Manufactured', 'Thargoid Carapace'),
    'tg_biomechanicalconduits': (3, 'Manufactured', 'Bio-Mechanical Conduits'),
    'chemicaldistillery': (3, 'Manufactured', 'Chemical Distillery'),
    'conductiveceramics': (3, 'Manufactured', 'Conductive Ceramics'),
    'electrochemicalarrays': (3, 'Manufactured', 'Electrochemical Arrays'),
    'focuscrystals': (3, 'Manufactured', 'Focus Crystals'),
    'guardian_sentinel_weaponparts': (3, 'Manufactured', 'Guardian Sentinel Weapon Parts'),
    'guardian_techcomponent': (3, 'Manufactured', 'Guardian Technology Component'),
    'heatexchangers': (3, 'Manufactured', 'Heat Exchangers'),
    'highdensitycomposites': (3, 'Manufactured', 'High Density Composites'),
    'mechanicalcomponents': (3, 'Manufactured', 'Mechanical Components'),
    'phasealloys': (3, 'Manufactured', 'Phase Alloys'),
    'precipitatedalloys': (3, 'Manufactured', 'Precipitated Alloys'),
    'shieldingsensors': (3, 'Manufactured', 'Shielding Sensors'),
    'unknownenergycell': (3, 'Manufactured', 'Thargoid Energy Cell'),
    'tg_wreckagecomponents': (3, 'Manufactured', 'Wreckage Components'),
    'chemicalmanipulators': (4, 'Manufactured', 'Chemical Manipulators'),
    'compoundshielding': (4, 'Manufactured', 'Compound Shielding'),
    'conductivepolymers': (4, 'Manufactured', 'Conductive Polymers'),
    'configurablecomponents': (4, 'Manufactured', 'Configurable Components'),
    'heatvanes': (4, 'Manufactured', 'Heat Vanes'),
    'polymercapacitors': (4, 'Manufactured', 'Polymer Capacitors'),
    'fedproprietarycomposites': (4, 'Manufactured', 'Proprietary Composites'),
    'protolightalloys': (4, 'Manufactured', 'Proto Light Alloys'),
    'refinedfocuscrystals': (4, 'Manufactured', 'Refined Focus Crystals'),
    'unknowntechnologycomponents': (4, 'Manufactured', 'Thargoid Technological Components'),
    'thermicalloys': (4, 'Manufactured', 'Thermic Alloys'),
    'tg_weaponparts': (4, 'Manufactured', 'Weapon Parts'),
    'biotechconductors': (5, 'Manufactured', 'Biotech Conductors'),
    'fedcorecomposites': (5, 'Manufactured', 'Core Dynamics Composites'),
    'exquisitefocuscrystals': (5, 'Manufactured', 'Exquisite Focus Crystals'),
    'imperialshielding': (5, 'Manufactured', 'Imperial Shielding'),
    'improvisedcomponents': (5, 'Manufactured', 'Improvised Components'),
    'militarygradealloys': (5, 'Manufactured', 'Military Grade Alloys'),
    'militarysupercapacitors': (5, 'Manufactured', 'Military Supercapacitors'),
    'pharmaceuticalisolators': (5, 'Manufactured', 'Pharmaceutical Isolators'),
    'tg_propulsionelement': (5, 'Manufactured', 'Propulsion Elements'),
    'protoheatradiators': (5, 'Manufactured', 'Proto Heat Radiators'),
    'protoradiolicalloys': (5, 'Manufactured', 'Proto Radiolic Alloys'),
    'unknownenergysource': (5, 'Manufactured', 'Sensor Fragment'),
    'unknownorganiccircuitry': (5, 'Manufactured', 'Thargoid Organic Circuitry'),
    # Raw
    'carbon': (1, 'Raw', 'Carbon'),
    'iron': (1, 'Raw', 'Iron'),
    'lead': (1, 'Raw', 'Lead'),
    'nickel': (1, 'Raw', 'Nickel'),
    'phosphorus': (1, 'Raw', 'Phosphorus'),
    'rhenium': (1, 'Raw', 'Rhenium'),
    'sulphur': (1, 'Raw', 'Sulphur'),
    'arsenic': (2, 'Raw', 'Arsenic'),
    'chromium': (2, 'Raw', 'Chromium'),
    'germanium': (2, 'Raw', 'Germanium'),
    'manganese': (2, 'Raw', 'Manganese'),
    'vanadium': (2, 'Raw', 'Vanadium'),
    'zinc': (2, 'Raw', 'Zinc'),
    'zirconium': (2, 'Raw', 'Zirconium'),
    'boron': (3, 'Raw', 'Boron'),
    'cadmium': (3, 'Raw', 'Cadmium'),
    'mercury': (3, 'Raw', 'Mercury'),
    'molybdenum': (3, 'Raw', 'Molybdenum'),
    'niobium': (3, 'Raw', 'Niobium'),
    'tin': (3, 'Raw', 'Tin'),
    'tungsten': (3, 'Raw', 'Tungsten'),
    'antimony': (4, 'Raw', 'Antimony'),
    'polonium': (4, 'Raw', 'Polonium'),
    'ruthenium': (4, 'Raw', 'Ruthenium'),
    'selenium': (4, 'Raw', 'Selenium'),
    'technetium': (4, 'Raw', 'Technetium'),
    'tellurium': (4, 'Raw', 'Tellurium'),
    'yttrium': (4, 'Raw', 'Yttrium'),
}


def info(symbol, localised=None):
    """(grade, kind, name, cap) for a journal material symbol; grade and cap
    are None for one this table doesn't know."""
    grade, kind, name = MATERIALS.get(str(symbol or "").lower(), (None, None, None))
    return grade, kind, (name or localised or str(symbol or "").title()).strip(), CAPS.get(grade)
